-- =============================================================
-- TABEL EKSKLUSIF UNTUK EDUPONGO (terpisah dari CMS-MASTER)
-- Jalankan di Supabase SQL Editor: https://supabase.com → project → SQL Editor
-- =============================================================

-- 1. edp_features — Fitur Solusi Lengkap (website homepage)
create table edp_features (
  id bigint generated by default as identity primary key,
  icon text not null default '✅',
  tag text not null,
  title text not null,
  desc text not null,
  tab text not null default 'semua',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 2. edp_testimonials — Testimoni sekolah (website homepage)
create table edp_testimonials (
  id bigint generated by default as identity primary key,
  text text not null,
  name text not null,
  role text not null default '',
  initial text not null default '',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 3. edp_faqs — FAQ (website homepage)
create table edp_faqs (
  id bigint generated by default as identity primary key,
  category text not null default 'umum',
  question text not null,
  answer text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 4. edp_why_cards — Kenapa Edupongo (website homepage)
create table edp_why_cards (
  id bigint generated by default as identity primary key,
  title text not null,
  desc text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 5. edp_problem_cards — Masalah yang diselesaikan (website homepage)
create table edp_problem_cards (
  id bigint generated by default as identity primary key,
  icon text not null default '📋',
  title text not null,
  description text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 6. edp_stats — Angka statistik (website homepage & about)
create table edp_stats (
  id bigint generated by default as identity primary key,
  num text not null,
  label text not null,
  page text not null default 'home',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- Index untuk sorting
create index idx_edp_features_sort on edp_features (sort_order);
create index idx_edp_testimonials_sort on edp_testimonials (sort_order);
create index idx_edp_faqs_sort on edp_faqs (sort_order);
create index idx_edp_why_cards_sort on edp_why_cards (sort_order);
create index idx_edp_problem_cards_sort on edp_problem_cards (sort_order);
create index idx_edp_stats_sort on edp_stats (sort_order);

-- RLS: izinkan anon untuk SELECT (baca data)
alter table edp_features enable row level security;
alter table edp_testimonials enable row level security;
alter table edp_faqs enable row level security;
alter table edp_why_cards enable row level security;
alter table edp_problem_cards enable row level security;
alter table edp_stats enable row level security;

create policy "anon_can_select_edp_features" on edp_features for select to anon using (true);
create policy "anon_can_select_edp_testimonials" on edp_testimonials for select to anon using (true);
create policy "anon_can_select_edp_faqs" on edp_faqs for select to anon using (true);
create policy "anon_can_select_edp_why_cards" on edp_why_cards for select to anon using (true);
create policy "anon_can_select_edp_problem_cards" on edp_problem_cards for select to anon using (true);
create policy "anon_can_select_edp_stats" on edp_stats for select to anon using (true);

-- =============================================================
-- ISI DATA AWAL (opsional — biar website langsung muncul konten)
-- =============================================================

-- edp_features (9 fitur untuk tab 'semua')
insert into edp_features (icon, tag, title, desc, tab, sort_order) values
('✅', 'Otomatis & Akurat', 'Presensi Digital — Manual, Fingerprint, atau GPS', 'Catat kehadiran ratusan siswa dan guru dalam hitungan detik. Pilih metode yang paling sesuai — ketiganya terintegrasi langsung ke laporan.', 'semua', 1),
('📊', 'Guru Fokus Ngajar', 'Rapor Digital — K13, Kurikulum Merdeka & Program Unggulan', 'Input nilai sekali, rapor terformat otomatis. Mendukung tiga kurikulum sekaligus — guru tidak perlu ulang format dari nol setiap ganti kebijakan.', 'semua', 2),
('🏫', 'Tanpa Antre, Tanpa Bolak-balik', 'PPDB Online — Pendaftaran, Berkas & Pengumuman Terpusat', 'Calon siswa daftar dari rumah, upload berkas dari HP. Sekolah verifikasi dan umumkan hasil dari satu dashboard — tanpa berkas fisik.', 'semua', 3),
('💳', 'Transparan & Real-Time', 'Pembayaran Terintegrasi — SPP, Tagihan & Laporan Otomatis', 'Orang tua bayar SPP dari aplikasi, bendahara lihat status real-time. Laporan keuangan tersedia kapanpun tanpa rekap manual.', 'semua', 4),
('🖥️', 'Nilai Langsung Keluar', 'Computer Based Test — Ujian Online & Analisa Butir Soal', 'Siswa ujian di komputer, hasil keluar otomatis. Guru bisa analisa butir soal langsung dari platform — tidak ada lagi koreksi manual.', 'semua', 5),
('📚', 'Satu Klik, Langsung Terkirim', 'Media Pembelajaran — Materi Tersimpan & Terbagi Mudah', 'Guru upload materi sekali, siswa akses dari aplikasi kapanpun. Tidak ada lagi kirim file lewat WhatsApp yang berantakan.', 'semua', 6),
('💬', 'Tidak Ada Info yang Telat', 'Live Chat & Pengumuman — Sekolah ke Orang Tua dalam Detik', 'Kirim pengumuman ke seluruh orang tua dalam satu klik. Live chat untuk komunikasi langsung antara guru, TU, dan orang tua.', 'semua', 7),
('📱', 'Pantau Dari Mana Saja', 'Aplikasi Orang Tua — Presensi, Rapor & Pembayaran di Satu Tempat', 'Orang tua tahu anak hadir atau tidak hari ini — tanpa telepon ke sekolah. Rapor, pengumuman, dan tagihan semua di satu aplikasi.', 'semua', 8),
('📖', 'Hemat Waktu Guru', 'Jurnal Mengajar Digital — Dokumentasi Kelas Tanpa Repot', 'Guru isi jurnal mengajar langsung dari HP dalam hitungan menit. Kepala sekolah pantau progress mengajar semua guru dari satu dashboard.', 'semua', 9);

-- Fitur tab Guru (6)
insert into edp_features (icon, tag, title, desc, tab, sort_order) values
('📖', 'Selesai dalam Menit', 'Jurnal Mengajar Digital', 'Isi jurnal mengajar langsung dari HP — tidak perlu buka laptop, tidak perlu tulis manual. Dokumentasi kelas selesai sebelum jam istirahat berakhir.', 'guru', 1),
('✅', 'Otomatis & Akurat', 'Presensi Siswa dari Aplikasi', 'Absen siswa langsung dari HP saat jam pelajaran dimulai. Tidak ada lagi kertas presensi yang bisa hilang atau rekap manual yang memakan waktu.', 'guru', 2),
('📊', 'Tidak Perlu Ulang Format', 'Rapor Digital — K13, Kurmer & Program Unggulan', 'Input nilai sekali, rapor terformat otomatis sesuai kurikulum yang berlaku. Tidak ada lagi lembur sampai tengah malam hanya untuk format rapor.', 'guru', 3),
('📚', 'Rapi & Mudah Diakses', 'Media Pembelajaran Digital', 'Upload materi, video, atau dokumen sekali — siswa bisa akses kapanpun dari aplikasi. Tidak perlu kirim ulang setiap pertemuan.', 'guru', 4),
('🖥️', 'Koreksi Nol Detik', 'Computer Based Test', 'Buat soal ujian di platform, siswa kerjakan online, nilai keluar otomatis. Guru bisa langsung lihat analisa hasil ujian per siswa dan per soal.', 'guru', 5),
('🪪', 'Tanpa Antre di TU', 'Perizinan PTK dari HP', 'Ajukan izin atau cuti langsung dari aplikasi — kepala sekolah approve dari dashboard mereka. Tidak perlu tanda tangan fisik bolak-balik.', 'guru', 6);

-- Fitur tab Kepsek (6)
insert into edp_features (icon, tag, title, desc, tab, sort_order) values
('📈', 'Satu Dashboard, Semua Data', 'Pantau Sekolah Secara Real-Time', 'Kehadiran siswa hari ini, progress jurnal mengajar guru, status pembayaran SPP, dan data PPDB — semua terlihat dari satu layar tanpa harus tanya ke masing-masing bagian.', 'kepsek', 1),
('🏫', 'Lebih Rapi, Lebih Cepat', 'Manajemen PPDB Terpusat', 'Kelola seluruh proses penerimaan siswa baru dari satu platform — dari pendaftaran, verifikasi berkas, seleksi, hingga pengumuman hasil. Transparan dan tercatat.', 'kepsek', 2),
('💰', 'Laporan Kapanpun Siap', 'Laporan Keuangan Real-Time', 'Lihat status tagihan, rekapitulasi pembayaran, dan laporan keuangan sekolah kapanpun tanpa harus minta ke bendahara. Data selalu up-to-date.', 'kepsek', 3),
('👥', 'Data Lengkap & Terstruktur', 'Manajemen Data Guru & Pegawai', 'Kelola data kepegawaian, presensi guru, jurnal aktivitas, dan perizinan dalam satu sistem. Tidak ada lagi data yang berceceran di berbagai file.', 'kepsek', 4),
('📢', 'Sampai dalam Detik', 'Pengumuman & Humas Digital', 'Kirim pengumuman ke orang tua, guru, atau seluruh warga sekolah dalam satu klik. Tidak ada lagi informasi yang telat atau tidak merata.', 'kepsek', 5),
('🎓', 'Lengkap & Terpusat', 'Data Siswa, Alumni & BK', 'Seluruh riwayat data siswa — dari penerimaan, akademik, bimbingan konseling, hingga alumni — tersimpan rapi dan mudah diakses kapanpun.', 'kepsek', 6);

-- Fitur tab Ortu (6)
insert into edp_features (icon, tag, title, desc, tab, sort_order) values
('📍', 'Tahu Setiap Hari', 'Data Presensi Anak Secara Real-Time', 'Orang tua tahu anak hadir atau tidak hari ini — langsung dari notifikasi HP. Tidak perlu telepon ke sekolah lagi hanya untuk cek kehadiran.', 'ortu', 1),
('📊', 'Tidak Perlu Tunggu Akhir Semester', 'Akses Rapor Digital Kapanpun', 'Lihat perkembangan akademik anak langsung dari aplikasi — tidak perlu tunggu hari pembagian rapor. Semua nilai dan catatan guru tersedia digital.', 'ortu', 2),
('💳', 'Bayar dari Mana Saja', 'Pembayaran SPP dari Aplikasi', 'Bayar tagihan sekolah langsung dari HP — tidak perlu bawa uang tunai atau antre di sekolah. Riwayat pembayaran tersimpan otomatis dan bisa dicek kapanpun.', 'ortu', 3),
('📢', 'Langsung Sampai, Tidak Telat', 'Pengumuman Sekolah Real-Time', 'Informasi dari sekolah sampai langsung ke HP orang tua begitu dikirim. Tidak ada lagi pengumuman yang terlewat karena tidak ada di grup WhatsApp.', 'ortu', 4),
('💬', 'Komunikasi Langsung', 'Live Chat dengan Guru & Sekolah', 'Tanya langsung ke wali kelas atau TU dari aplikasi — semua percakapan tercatat rapi. Tidak perlu cari nomor WhatsApp pribadi guru lagi.', 'ortu', 5),
('🙋', 'Tanpa Harus Datang ke Sekolah', 'Perizinan Anak dari HP', 'Ajukan izin tidak masuk langsung dari aplikasi — guru langsung menerima notifikasi dan status izin tercatat otomatis di sistem presensi sekolah.', 'ortu', 6);

-- edp_testimonials
insert into edp_testimonials (text, name, role, initial, sort_order) values
('Proses PPDB yang biasanya memakan waktu berminggu-minggu dan bikin orang tua antre panjang: sekarang bisa selesai lebih cepat, lebih rapi, dan orang tua tidak perlu datang berkali-kali.', 'Kepala Sekolah: SMP Islam An Nawawiyah', 'Rembang, Jawa Tengah', 'B', 1),
('Guru-guru kami dulu menghabiskan berjam-jam hanya untuk rekap presensi dan input rapor. Sekarang mereka punya waktu lebih untuk fokus ke hal yang seharusnya jadi tugas utama mereka: mengajar.', 'Kepala Sekolah: MA Plus Al Hadi', 'Bojonegoro, Jawa Timur', 'A', 2),
('Yang paling saya suka adalah orang tua sekarang bisa langsung tahu kalau anaknya tidak hadir. Dulu mereka baru tahu kalau sudah telepon ke sekolah: dan kadang kami sendiri yang kewalahan mengangkat telepon.', 'Wakil Kepala Sekolah: MA Unggulan Wahab Hasbulloh', 'Jombang, Jawa Timur', 'W', 3);

-- edp_faqs
insert into edp_faqs (category, question, answer, sort_order) values
('umum', 'Apakah Edupongo cocok untuk pesantren dan boarding school?', 'Ya: dan ini justru yang membedakan Edupongo dari platform manajemen sekolah lainnya. Edupongo dirancang dari awal untuk memahami ekosistem pesantren: dari manajemen santri, koordinasi asrama, hingga integrasi yayasan dalam satu sistem. Sudah dipakai oleh beberapa pondok pesantren dan boarding school di Jawa.', 1),
('umum', 'Jenjang sekolah apa saja yang bisa menggunakan Edupongo?', 'Edupongo mendukung semua jenjang: <strong>RA/TK, MI/SD, MTs/SMP, MA/SMA, dan SMK</strong>: baik negeri maupun swasta. Termasuk PKBM dan lembaga pendidikan nonformal lainnya. Satu platform yang sama bisa dipakai oleh seluruh unit di bawah satu yayasan.', 2),
('umum', 'Apakah Edupongo mendukung Kurikulum Merdeka?', 'Ya. Edupongo mendukung <strong>tiga kurikulum sekaligus</strong>: Kurikulum 13, Kurikulum Merdeka, dan Program Unggulan. Format rapor menyesuaikan otomatis sesuai kurikulum yang dipilih per kelas atau per rombel.', 3),
('umum', 'Sudah berapa lama Edupongo beroperasi?', 'Edupongo telah mendampingi sekolah-sekolah di Indonesia <strong>sejak 2014</strong>: lebih dari 10 tahun. Platform kami juga telah terdaftar <strong>HaKI di Kemenkumham RI</strong>.', 4),
('fitur', 'Metode presensi apa saja yang tersedia?', 'Edupongo menyediakan tiga metode presensi: <strong>Presensi manual</strong> via portal website, <strong>presensi fingerprint</strong>, dan <strong>presensi berbasis lokasi GPS</strong> melalui aplikasi mobile.', 1),
('fitur', 'Bagaimana cara orang tua mengakses informasi anak?', 'Orang tua cukup download <strong>aplikasi Edupongo</strong> di Google Play Store atau App Store. Dari satu aplikasi, mereka bisa memantau kehadiran harian anak, melihat rapor digital, membayar tagihan SPP, dan berkomunikasi langsung dengan guru.', 2),
('fitur', 'Apakah ada fitur ujian online (CBT)?', 'Ya. Edupongo dilengkapi fitur <strong>Computer Based Test (CBT)</strong>: guru bisa membuat bank soal, menjadwalkan ujian, dan hasilnya keluar otomatis. Tersedia juga fitur analisa butir soal.', 3),
('fitur', 'Apakah ada aplikasi mobile untuk guru?', 'Ada. Edupongo menyediakan <strong>aplikasi mobile terpisah untuk guru</strong> yang mencakup presensi siswa, jurnal mengajar, media pembelajaran, dan perizinan PTK.', 4),
('implementasi', 'Berapa lama proses implementasi di sekolah?', 'Durasi implementasi bervariasi tergantung skala sekolah. <strong>Tim Edupongo mendampingi penuh</strong> dari awal hingga sekolah siap mandiri: mulai dari setup sistem, migrasi data, pelatihan, hingga go-live.', 1),
('implementasi', 'Apakah ada pelatihan untuk guru dan operator sekolah?', 'Ya. Setiap sekolah yang bergabung mendapatkan <strong>sesi pelatihan langsung</strong> untuk operator dan guru. Tim kami juga menyediakan panduan dan dokumentasi yang bisa diakses kapanpun.', 2),
('implementasi', 'Bagaimana cara memulai dengan Edupongo?', 'Langkah pertama adalah <strong>jadwalkan sesi demo gratis</strong> bersama tim kami. Hubungi kami di <strong>contact@edupongo.com</strong> atau klik tombol "Jadwalkan Demo" di halaman ini.', 3),
('keamanan', 'Apakah data siswa aman di Edupongo?', 'Keamanan data adalah prioritas utama kami. Seluruh data <strong>dienkripsi dan dikelola dengan standar keamanan ketat</strong>. Platform Edupongo telah terdaftar sebagai <strong>HaKI di Kemenkumham RI</strong>.', 1),
('keamanan', 'Siapa saja yang bisa mengakses data sekolah?', 'Akses data diatur dengan sistem <strong>role-based access control</strong>: setiap pengguna hanya bisa melihat data sesuai perannya. Kepala sekolah punya akses penuh, guru hanya bisa akses kelasnya, orang tua hanya data anak mereka.', 2),
('keamanan', 'Apa yang terjadi dengan data jika berhenti berlangganan?', 'Seluruh data tetap menjadi milik sekolah. Tim Edupongo akan membantu proses <strong>ekspor data secara lengkap</strong> dalam format yang bisa digunakan.', 3);

-- edp_why_cards
insert into edp_why_cards (title, desc, sort_order) values
('Administrasi lebih efisien, data tersimpan rapi', 'Semua data siswa, guru, dan keuangan tersimpan terpusat dan mudah diakses kapanpun: tidak ada lagi data yang berserakan di berbagai file Excel.', 1),
('PPDB tanpa antre: dari mana saja, kapan saja', 'Proses penerimaan siswa baru yang biasanya butuh berminggu-minggu bisa diselesaikan lebih cepat, lebih rapi, dan lebih transparan.', 2),
('Orang tua terhubung langsung dengan sekolah', 'Tidak ada lagi informasi yang telat sampai. Orang tua bisa pantau kehadiran, nilai, dan tagihan anak langsung dari HP mereka.', 3),
('Presensi fleksibel: 3 metode dalam satu platform', 'Manual via web, fingerprint untuk sekolah yang sudah punya mesin, atau GPS berbasis lokasi di aplikasi mobile. Pilih yang paling cocok.', 4),
('Satu-satunya yang cover ekosistem pesantren', 'Edupongo dirancang untuk memahami kebutuhan unik pesantren dan boarding school: dari manajemen santri hingga koordinasi asrama dan yayasan.', 5),
('Terpercaya sejak 2014: bukan startup kemarin sore', '10+ tahun mendampingi sekolah di Indonesia. HaKI terdaftar, lolos seleksi RISTEK-BRIN, dan terus berkembang bersama kebutuhan sekolah.', 6);

-- edp_problem_cards
insert into edp_problem_cards (icon, title, description, sort_order) values
('📋', 'Rekap presensi manual setiap hari', 'Guru menghabiskan puluhan menit hanya untuk mencatat kehadiran siswa di buku: padahal itu bisa otomatis.', 1),
('📝', 'Rapor dikerjakan sampai larut malam', 'Input nilai satu per satu, format berbeda tiap kurikulum, dan deadline yang selalu mepet membuat guru kelelahan.', 2),
('🏫', 'PPDB bikin orang tua antre berjam-jam', 'Pendaftaran manual, berkas fisik yang bisa hilang, dan pengumuman yang tidak merata: pengalaman yang tidak perlu terjadi.', 3),
('📱', 'Orang tua tidak tahu aktivitas anak', 'Info dari sekolah telat, atau harus telepon dulu. Padahal orang tua yang terhubung = anak yang lebih berprestasi.', 4),
('💰', 'Laporan keuangan tidak transparan', 'Rekap SPP manual, tagihan yang sering tidak akurat, dan laporan yang butuh waktu berminggu-minggu untuk disiapkan.', 5),
('💻', 'Ujian masih di kertas, koreksi manual', 'Guru mengkoreksi ratusan lembar jawaban satu per satu: sementara hasilnya bisa keluar otomatis kalau pakai sistem yang tepat.', 6);

-- edp_stats
insert into edp_stats (num, label, page, sort_order) values
('100+', 'Sekolah aktif', 'home', 1),
('30rb+', 'Pengguna aktif', 'home', 2),
('10+', 'Tahun pengalaman', 'home', 3),
('HaKI', 'Terdaftar Kemenkumham', 'home', 4),
('10+', 'Tahun Pengalaman', 'about', 1),
('100+', 'Sekolah se-Indonesia', 'about', 2),
('30rb+', 'Pengguna Aktif', 'about', 3);

-- =============================================================
-- KOLOM TAMBAHAN UNTUK ADMIN CMS
-- =============================================================
alter table edp_testimonials add column if not exists status text not null default 'terbit';
alter table edp_testimonials add column if not exists publisher text not null default 'Admin';
alter table edp_testimonials add column if not exists date date;

alter table edp_faqs add column if not exists status text not null default 'terbit';
alter table edp_faqs add column if not exists publisher text not null default 'Admin';
alter table edp_faqs add column if not exists date date;

-- =============================================================
-- RLS POLICIES UNTUK INSERT / UPDATE / DELETE (admin write)
-- =============================================================
create policy if not exists "anon_can_insert_edp_testimonials" on edp_testimonials for insert to anon with check (true);
create policy if not exists "anon_can_update_edp_testimonials" on edp_testimonials for update to anon using (true);
create policy if not exists "anon_can_delete_edp_testimonials" on edp_testimonials for delete to anon using (true);

create policy if not exists "anon_can_insert_edp_faqs" on edp_faqs for insert to anon with check (true);
create policy if not exists "anon_can_update_edp_faqs" on edp_faqs for update to anon using (true);
create policy if not exists "anon_can_delete_edp_faqs" on edp_faqs for delete to anon using (true);

create policy if not exists "anon_can_insert_edp_blog" on edp_blog for insert to anon with check (true);
create policy if not exists "anon_can_update_edp_blog" on edp_blog for update to anon using (true);
create policy if not exists "anon_can_delete_edp_blog" on edp_blog for delete to anon using (true);

-- =============================================================
-- 7. edp_partners — Partner Sekolah (website homepage & CMS)
-- =============================================================
create table if not exists edp_partners (
  id bigint generated by default as identity primary key,
  name text not null,
  kota text not null default '',
  warna text not null default '#3498DB',
  foto text,
  status text not null default 'terbit',
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz default now()
);

create index if not exists idx_edp_partners_sort on edp_partners (sort_order);

alter table edp_partners enable row level security;

create policy "anon_can_select_edp_partners" on edp_partners for select to anon using (true);
create policy "auth_can_insert_edp_partners" on edp_partners for insert to authenticated with check (true);
create policy "auth_can_update_edp_partners" on edp_partners for update to authenticated using (true);
create policy "auth_can_delete_edp_partners" on edp_partners for delete to authenticated using (true);

-- =============================================================
-- 8. BLOG LIKES — Kolom + RPC Function
-- Jalankan di Supabase SQL Editor
-- =============================================================

-- Tambah kolom likes ke edp_blog
alter table edp_blog add column if not exists likes integer not null default 0;

-- RPC function: increment likes tanpa expose UPDATE ke anon
-- SECURITY DEFINER = jalan dengan hak owner function, bukan caller
create or replace function increment_blog_likes(blog_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update edp_blog
  set likes = coalesce(likes, 0) + 1
  where id = blog_id;
end;
$$;

-- Izinkan user anon (pengunjung publik) panggil function ini
grant execute on function increment_blog_likes(bigint) to anon;
