-- Buat table demo_requests di Supabase SQL Editor
-- Buka https://supabase.com → project → SQL Editor → paste ini → Run

-- 1. Buat table
create table demo_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  school text not null,
  position text,
  students text,
  created_at timestamptz default now()
);

-- 2. Index biar bisa diurutkan dari yang terbaru
create index idx_demo_requests_created_at on demo_requests (created_at desc);

-- 3. Izinkan siapapun (anon) insert data — RLS
alter table demo_requests enable row level security;

create policy "insert_public_demo_requests"
  on demo_requests
  for insert
  to anon
  with check (true);
